# Generated by Django 4.0.2 on 2023-04-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_selling_price_product_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='lawyer_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='school',
        ),
    ]
