# Generated by Django 4.0.2 on 2023-04-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_product_image_product_lawyer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('A', 'A'), ('B', 'B')], max_length=2),
        ),
    ]
